name: Company Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'app/company/backend/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login \
          -u "${{ secrets.DOCKERHUB_USERNAME }}" \
          --password-stdin

      - name: Build and Push Backend
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/ex8-company-backend"
          TAG="${GITHUB_SHA::7}"

          docker build \
            -t "$IMAGE:$TAG" \
            -t "$IMAGE:latest" \
            app/company/backend

          docker push "$IMAGE:$TAG"
          docker push "$IMAGE:latest"

          echo "TAG=$TAG" >> "$GITHUB_ENV"

      - name: Update Kubernetes Manifest
        run: |
          sed -i \
          "s|image: .*ex8-company-backend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/ex8-company-backend:${TAG}|" \
          k8s/company/backend-deployment.yaml

      - name: Commit Kubernetes Manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add k8s/company/backend-deployment.yaml

          if git diff --cached --quiet; then
            echo "No manifest changes"
            exit 0
          fi

          git commit -m "Update backend image to ${TAG}"
          git push origin main
